import React from 'react';
import { SectionLabel, GoldButton } from './HeroSection';
export const Footer = ({ onOpenSponsorshipModal, onNavigate }) => {
    return (React.createElement("footer", { id: "footer", style: { background: '#062B4A' } },
        React.createElement("div", { className: "px-5 sm:px-8 md:px-12 py-16 border-b", style: { borderColor: 'rgba(214,145,3,0.2)' } },
            React.createElement("div", { className: "max-w-4xl mx-auto text-center" },
                React.createElement(SectionLabel, { text: "KEMITRAAN" }),
                React.createElement("h2", { className: "font-mileast italic font-bold mt-4 leading-tight gold-text", style: { fontSize: 'clamp(2rem, 5vw, 56px)' } },
                    "Dukung Mahakarya",
                    React.createElement("br", null),
                    "Santri Gontor"),
                React.createElement("p", { className: "font-baskerville text-sm mt-4 mb-8 max-w-xl mx-auto", style: { color: 'rgba(244,241,235,0.75)' } }, "Jadilah mitra sponsorship dan saksikan pagelaran seni budaya akbar siswa kelas 5 KMI Pondok Modern Darussalam Gontor."),
                React.createElement(GoldButton, { onClick: onOpenSponsorshipModal, label: "AJUKAN SPONSORSHIP" }))),
        React.createElement("div", { className: "px-5 sm:px-8 md:px-12 py-12" },
            React.createElement("div", { className: "max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-10" },
                React.createElement("div", null,
                    React.createElement("div", { className: "font-mileast italic text-3xl font-bold gold-text mb-2" }, "Drama Arena"),
                    React.createElement("div", { className: "font-cormorant-sc text-xs tracking-widest uppercase mb-3", style: { color: 'rgba(214,145,3,0.7)' } }, "5102 \u00B7 Kelas 5 KMI PMDG"),
                    React.createElement("p", { className: "font-baskerville text-xs leading-relaxed", style: { color: 'rgba(244,241,235,0.6)' } }, "\"Naluri dan Nurani\" \u2014 Sadar akan nilai perjuangan, tumbuhkan semangat kebersamaan.")),
                React.createElement("div", null,
                    React.createElement("div", { className: "font-cormorant-sc text-xs tracking-widest uppercase mb-4", style: { color: '#D69103' } }, "Navigasi"),
                    React.createElement("ul", { className: "flex flex-col gap-2" }, [
                        ['Profil PMDG', 'about'],
                        ['Tema & Filosofi', 'theme'],
                        ['Ragam Acara', 'shows'],
                        ['Susunan Panitia', 'committee']
                    ].map(([label, id]) => (React.createElement("li", { key: id },
                        React.createElement("button", { onClick: () => onNavigate(id), className: "font-cormorant-sc text-xs tracking-wide hover:text-yellow-400 transition-colors cursor-pointer", style: { color: 'rgba(244,241,235,0.7)' } }, label)))))),
                React.createElement("div", null,
                    React.createElement("div", { className: "font-cormorant-sc text-xs tracking-widest uppercase mb-4", style: { color: '#D69103' } }, "Lokasi"),
                    React.createElement("p", { className: "font-baskerville text-xs leading-relaxed", style: { color: 'rgba(244,241,235,0.7)' } },
                        "Pondok Modern Darussalam Gontor",
                        React.createElement("br", null),
                        "Ponorogo, Jawa Timur 63472",
                        React.createElement("br", null),
                        "www.gontor.ac.id")),
                React.createElement("div", null,
                    React.createElement("div", { className: "font-cormorant-sc text-xs tracking-widest uppercase mb-4", style: { color: '#D69103' } }, "Narahubung"),
                    React.createElement("div", { className: "flex flex-col gap-2 font-baskerville text-xs", style: { color: 'rgba(244,241,235,0.7)' } },
                        React.createElement("p", null,
                            "Ahmad Nur Fajar D. P.",
                            React.createElement("br", null),
                            "0813-9850-7876"),
                        React.createElement("p", null, "dramaarena5102@gontor.ac.id"),
                        React.createElement("p", { className: "mt-2 font-bold", style: { color: '#D69103' } }, "Rek. BRI: 0070-01-000315-56-7"))))),
        React.createElement("div", { className: "px-5 sm:px-8 py-5 text-center text-xs font-cormorant-sc tracking-widest uppercase", style: { borderTop: '1px solid rgba(214,145,3,0.15)', color: 'rgba(244,241,235,0.4)' } }, "\u00A9 2026 Pagelaran Seni Drama Arena 5102 \u00B7 Pondok Modern Darussalam Gontor \u00B7 Naluri dan Nurani")));
};
